# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Scattered Media Gallery"
  description: An image gallery where the images are scattered randomly
  icon:
  tags: []
  tabbed: true

# Defines the structure of this component, as well as the default values
blueprint:
  _componentId: scatterGallery-e67d93a5-7ea1-4230-990b-72427ef2f030
  content:
    showNote: true
    sectionId:
    heading: bookshop:structure:headingBlocks
    images: [bookshop:generic/image]
    buttons: [bookshop:structure:buttons]
  styles:
    color_group: primary
    galleryStyling:
      imageModal: true
      photoSize: 500
      borderSize: 10
      arstr: 1
      showInfo: false
      infoStyle: 1
      autoSlide: false
      duration: 2


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
