# Metadata about this component, to be used in the CMS
spec:
  structures:
    - grid_items
  label: "Grid Item"
  description: Individual item within a grid layout
  icon: check_box_outline_blank
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    contentSections:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    contentSections:
      - _bookshop_name: building-blocks/core-elements/heading
        content:
          text: Grid Item
          level: h3
        styles:
          size: md
      - _bookshop_name: building-blocks/core-elements/text
        content:
          text: Content inside this grid item.

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  contentSections:
    type: array
    label: Content
    comment: Content sections within this grid item
    options:
      structures: _structures.content_sections
